### ISSUE TITLE
加载宏包 amsmath 后在数学模式产生字体警告

### ISSUE THREAD

**Issue by afsagse** [CTeX-org/ctex-kit#693] opened 2024-01-29 00:43 UTC
平台：windows10，TeXLive2023
加载 amsmath 宏包后在数学模式会出现字体警告
Size substitutions with differences
(Font)	up to 0.41063pt have occurred.
Font shape `OMX/cmex/m/n' in size <10.53937> not available
(Font)	size <10.95> substituted.

```
\documentclass{ctexbook}
\usepackage{amsmath}

\begin{document}

$abcd$

\end{document}
```

**Comment by muzimuzhi** [comment] 2024-01-29 07:58
Duplicate of #459.

**Closed** 2024-01-29 07:58 UTC

**Comment by afsagse** [comment] 2024-01-29 09:44
> Duplicate of #459
好的，谢谢
