### ISSUE TITLE
Highlight glitch with `\CJKsout` or `\CJKunderanyline` (chop out a portion of punctuation marks)

### ISSUE THREAD

**Issue by amalgame21** [CTeX-org/ctex-kit#672] opened 2023-07-29 11:18 UTC
```tex
\documentclass{article}
\usepackage[margin=1in]{geometry}
\usepackage{xeCJK}
\usepackage{xcolor}
\usepackage{xeCJKfntef}
% \newcommand*{\hl}[1]{\CJKsout*[thickness=2.5ex, format=\color{yellow}]{#1}}
\newcommand*{\hl}[1]{\CJKunderanyline*{0.5ex}{\color{yellow}\rule{2pt}{2.8ex}}{#1}}

\begin{document}
\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」}\hl{「你」} 
\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。}\hl{我。} 

「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」「你」 
我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。我。 
\end{document}

```
Result:
![xeCJK](https://github.com/CTeX-org/ctex-kit/assets/93383215/bbf47a76-1d72-4f74-a2c0-d6445d52e0cc)

Also in the manual (install `texlive-doc` in arch linux, and run `texdoc xecjk` in terminal to show this manual):
![xeCJK2](https://github.com/CTeX-org/ctex-kit/assets/93383215/af385507-8abb-471f-a8a5-ec89f2a46542)

**Comment by stone-zeng** [comment] 2023-07-29 13:43
Duplicate of #308.

**Closed by stone-zeng** 2023-07-29 13:43 UTC
