### ISSUE TITLE
XeTeX 下使用思源黑体 / 思源宋体后复制出错

### ISSUE THREAD

**Issue by Stone-Zeng** [CTeX-org/ctex-kit#286] opened 2017-06-10 13:47 UTC
代码如下：
```latex
\documentclass{ctexart}
\begin{document}
    {\CJKfontspec{Source Han Sans SC} 孤立子 ABC} \par
    {\CJKfontspec{Source Han Serif SC} 孤立子 ABC} \par
    {\CJKfontspec{Microsoft YaHei} 孤立子 ABC} \par
    孤立子 ABC
\end{document}
```
使用 XeLaTeX 编译后，前两行复制出来三个汉字是 `U+5B64`、`U+2F74` 和 `U+2F26`，后两行则是 `U+5B64`、`U+7ACB` 和 `U+5B50`。在思源黑体 / 宋体之下“立子”二字变成了康熙部首（`U+2F74` 和 `U+2F26`）。在只用 `fontspec` 的情况下，也同样有该问题。

使用 LuaLaTeX 编译，则正常。

PDF 阅读器方面，Adobe Reader 和 SumatraPDF 都会出现错误。

平台：Windows 10，TeX Live 2017，XeTeX 3.14159265-2.6-0.99998，LuaTeX 1.0.4。
字体：Source Han Sans 1.004，Source Han Serif 1.000。

**Comment by leo-liu** [comment] 2017-06-11 14:50
应该是 XeTeX 的 Bug。裸 XeTeX 就能重现。
```
% XeTeX
\font\1="Source Han Sans SC"
\font\2="Source Han Serif SC"
\font\3="Microsoft YaHei"

{\1 孤立子 ABC} \par
{\2 孤立子 ABC} \par
{\3 孤立子 ABC} \par

\bye
```

无论如何，ctex-kit 项目无法解决这类问题。

另外，似乎不是 `dvipdfmx` 的 Bug，因为用 uptex + dvipdfmx 可以测试通过如下代码无误：
```
% upTeX + dvipdfmx
\font\rm=upzhserif-h
\font\it=upzhserifit-h
\font\bf=upzhserifb-h

\special{pdf:mapline upserif-h   unicode SourceHanSansSC-Regular.otf}
\special{pdf:mapline upserifit-h unicode SourceHanSerifSC-Regular.otf}
\special{pdf:mapline upserifb-h  unicode msyh.ttc}

{\rm 孤立子 ABC} \par
{\it 孤立子 ABC} \par
{\bf 孤立子 ABC} \par

\bye
```

**Comment by leo-liu** [comment] 2017-06-11 15:24
经马起园确认，是 XeTeX 在 CMap 方面的 bug。

**Comment by jjgod** [comment] 2017-06-11 18:57
Pretty sure I have fixed this at least once, has it regressed again?

**Comment by jjgod** [comment] 2017-06-11 19:00
As a workaround, does `\XeTeXgenerateactualtext=1` help in this case?

**Comment by jjgod** [comment] 2017-06-11 23:02
It appears that my SourceHanSansSC-Regular.otf and SourceHanSerifSC-Regular.otf of exactly the same versions don’t have this problem at all, all the reverse lookup worked perfectly fine:

	cffont: 0x7fc883ca0350, cid = 15785, gid = 15785, ch = 12070
	cffont: 0x7fc883ca0350, cid = 29992, gid = 29992, ch = 12148
	cffont: 0x7fc883ca0350, cid = 15824, gid = 15824, ch = 23396
	cffont: 0x7fc883e5ff10, cid = 15539, gid = 15539, ch = 12070
	cffont: 0x7fc883e5ff10, cid = 30354, gid = 30354, ch = 12148
	cffont: 0x7fc883e5ff10, cid = 15567, gid = 15567, ch = 23396

**Comment by Stone-Zeng** [comment] 2017-06-12 00:17
`\XeTeXgenerateactualtext=1` not work on my computer. I use SourceHanSans-Regular.ttc and SourceHanSerif-Regular.ttc.

By the way, I have noticed that you have modified TeX Live. When this change can take effect?

**Comment by jjgod** [comment] 2017-06-12 00:56
I modified my branch of texlive as an attempt, I’m not convinced that this is the best approach yet.

In general, TeXLive has an annual release schedule so any changes done now will be released next year.

**Comment by leo-liu** [comment] 2017-06-12 03:47
这个问题的解决似乎从 XeTeX 那边着手更合理一些，毕竟 (up)latex+dvipdfmx 也不会出错，是 XeTeX 编译时丢失了一部分信息。在 dvipdfm-x 打补丁有点怪。

**Comment by jjgod** [comment] 2017-06-12 04:16
For the record, I’m not able to reproduce the issue even with Adobe Reader on macOS.

**Comment by jjgod** [comment] 2017-06-12 14:46
http://tug.org/pipermail/xetex/2017-June/027143.html claimed that `\XeTeXgenerateactualtext=1` works fine. Can either of you try?

**Comment by Stone-Zeng** [comment] 2017-06-12 15:23
I have tried some PDF viewers. With `\XeTeXgenerateactualtext=1`,
**Adobe Reader DC**, **Adobe Acrobat DC** will give the correct result, while **SumatraPDF v3.1.2**, **Windows Reader App** (阅读器), **Microsoft Edge** and **Microsoft Word 2016** will not.

My OS is Windows 10 1607 (Build 14393.1198).

**Comment by jjgod** [comment] 2017-06-12 16:55
Thanks for testing again. I will see if Akira-san can build a new w32tex binary for `xdvipdfmx` for you to test.

**Comment by jjgod** [comment] 2017-06-12 22:50
Akira-san kindly confirms my patch indeed helped the `\XeTeXgenerateactualtext=0` situation and provided a new `dvipdfmx.dll` to use: http://tug.org/pipermail/xetex/2017-June/027150.html

Feel free to try.

Since it's not a ctex-kit bug I will close this and move further discussion elsewhere. If you have more to comment please reply to the email thread.

**Closed by jjgod** 2017-06-12 22:50 UTC
Labels: question

**Comment by leo-liu** [comment] 2017-06-13 02:37
Windows 下测试了一下，`\XeTeXgenerateactualtext=1` 在 Debian 下有效。（Acroread 9.5, Evince 3.22.1）

**Comment by Stone-Zeng** [comment] 2018-04-11 10:28
I have tested on TeX Live 2018 (revision 47303 2018-04-05 19:52:22 +0200) and XeTeX (3.14159265-2.6-0.99999).

Test file:

```tex
% Compiled with XeTeX
% \XeTeXgenerateactualtext=0 or 1

\font\1="Source Han Sans SC"  % 1.004
\font\2="Source Han Serif SC" % 1.001
\font\3="Microsoft YaHei"

\def\KANGXI{%
  ⽴% U+2F74
  ⼦% U+2F26
}

\def\HAN{%
  立% U+7ACB
  子% U+5B50
}

{\1 \KANGXI ~ \HAN} \par
{\2 \KANGXI ~ \HAN} \par
{\3 \KANGXI ~ \HAN} \par

\bye
```

Copy the string in PDF files to <https://r12a.github.io/app-conversion/>, the results are the following:

- Adobe Acrobat Pro DC (2018.011.20038):

```tex
% \XeTeXgenerateactualtext=1
U+2F74 U+2F26 U+7ACB U+5B50
U+2F74 U+2F26 U+7ACB U+5B50
U+2F74 U+2F26 U+7ACB U+5B50

% \XeTeXgenerateactualtext=0
U+7ACB U+5B50 U+7ACB U+5B50
U+7ACB U+5B50 U+7ACB U+5B50
U+107419 U+107316 U+7ACB U+5B50
```

- SumatraPDF (3.1.2 64-bit)

```tex
% \XeTeXgenerateactualtext=1
U+7ACB U+5B50 U+7ACB U+5B50
U+7ACB U+5B50 U+7ACB U+5B50
?? U+7ACB U+5B50

% \XeTeXgenerateactualtext=0
U+7ACB U+5B50 U+7ACB U+5B50
U+7ACB U+5B50 U+7ACB U+5B50
?? U+7ACB U+5B50
```

- Google Chrome (65.0.3325.181)

```tex
% \XeTeXgenerateactualtext=1
U+2F74 U+2F26 U+7ACB U+5B50
U+2F74 U+2F26 U+7ACB U+5B50
U+2F74 U+2F26 U+7ACB U+5B50

% \XeTeXgenerateactualtext=0
U+7ACB U+5B50 U+7ACB U+5B50
U+7ACB U+5B50 U+7ACB U+5B50
U+7419 U+7316 U+7ACB U+5B50
```

- Microsoft Edge (41.16299.334.0)

```tex
% \XeTeXgenerateactualtext=1
U+7ACB U+5B50 U+7ACB U+5B50
U+7ACB U+5B50 U+7ACB U+5B50
  U+7ACB U+5B50

% \XeTeXgenerateactualtext=0
U+7ACB U+5B50 U+7ACB U+5B50
U+7ACB U+5B50 U+7ACB U+5B50
  U+7ACB U+5B50
```

Notice that for normal Han characters, all programs give the correct results; for Kangxi Radicals, however, it seems that the mapping is still in a mess.

**Comment by muzimuzhi** [comment] 2019-12-06 15:43
`\XeTeXgenerateactualtext=1` 的工作原理是向 pdf 写入 `/ActualText` 项（pdf ref v1.7, sec. 10.6.2, table 10.10; sec. 10.8.3），从而可以逐字符地控制从 PDF 复制文本的结果。写入 `/ActualText` 项后，「复制出错」的问题能否修复，还需要阅读器支持。

PS：从对 [SumatraPDF 源码](https://github.com/sumatrapdfreader/sumatrapdf)的简单搜索看，它仍不支持 `/ActualText`。

------
关于 `\XeTeXgenerateactualtext` 的部分资料（至少还有一个印象中的邮件没有找到）
 - 最初的 feature request [邮件](https://tug.org/pipermail/xetex/2016-February/026398.html)
   - [提到](https://tug.org/pipermail/xetex/2016-February/026445.html)该功能需要阅读器配合
 - primitive 添加时的通知[邮件](https://tug.org/pipermail/xetex/2016-February/026451.html)
   - [提到](https://tug.org/pipermail/xetex/2016-February/026466.html)开启该功能后，在不同阅读器中对「选中文本、标记文本」等操作的影响
 - xetex news 中的[相关描述](https://www.tug.org/svn/texlive/trunk/Build/source/texk/web2c/xetexdir/NEWS?view=markup#l68)
 - 要求将 `\XeTeXgenerateactualtext` 文档化的 [xetexref issue](https://github.com/wspr/xetexref/issues/7)
